services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust

  nextjs-app:
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
